### ISSUE TITLE
Error when trying to install fora

### ISSUE THREAD

**Issue by prabinv** [nodejam/nodejam#26]
I'm running this on a Mac OS X Yosemite, on Node 0.12.4

I installed fora globally, but got error on the `fora install fora-template-fora-appstore` command

``` bash
fora install fora-template-fora-appstore
/usr/local/lib/node_modules/fora/lib/fora.js:22
const argv = _optimist2["default"].argv;
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

```

Any ideas why this might be happening?

**Comment by ak7** [comment]
Most of the dev and testing was with io.js. Could you please switch to io.js and try?

**Comment by jeswin** [comment]
Node and iojs projects are merging soon. So until then, we'll just recommend iojs.
